### ISSUE TITLE
Главная страница

### ISSUE THREAD

**Issue by OlgaGost** [torin-asakura/bogorodsky#14]
Убрать нижний блок, Сделать два окошка вместо этого для статей по типу главных событий. Поставить внизу банеры СМИ: Богородские вести, 360 Богородский, радио-ногинск.

**Comment by TorinAsakura** [comment]
@OlgaGost а банеры где?

**Comment by TorinAsakura** [comment]
Так как вопрос с мёртвый точки не сдвинулся - закрываю
