### ISSUE TITLE
История

### ISSUE THREAD

**Issue by OlgaGost** [torin-asakura/bogorodsky#15]
https://disk.yandex.ru/d/J6SrXdk41-qGEQ

**Comment by TorinAsakura** [comment]
@OlgaGost ссылку будь добра

**Comment by OlgaGost** [comment]
Достопримечательности

Богородский городской округ с центром в Ногинске сформировался, как часть - наследник территории дореволюционного Богородского уезда. 
На Богородской земле тесно переплетается красота полей, лесных угодий, уникальных по красоте парков и богатство истории, которую хранят старинные здания, улочки, многовековые деревья.
Туристу здесь есть что посмотреть. Великолепные парки, музеи, театр. В изобилии сохранилась в Богородском округе архитектура в стиле модерн: здание Новоткацкой фабрики, женcкая гимназия, родильный дом, фабричное училище и многие другие. В то же время здесь - современная и хорошо развитая инфраструктура. Любители активного отдыха смогут отдохнуть у многочисленных водоемов.
Фото - Новоткацкая фабрика
До революции Ногинск (Богородск) был центром старообрядчества и текстильной промышленности. В 1840 году бывший крепостной Захар Морозов основал здесь текстильную мануфактуру. 
На берегах Клязьмы в 19 веке появились первые текстильные фабрики - Орехово-Зуево, Щелково, Павловский Посад. В Ногинске был реализован полный цикл текстильного производства. 
На текстильных фабриках Ногинска, кстати, снимали кино с Любовью Орловой "Светлый путь"(1940), "Москва слезам не верит"(1980). А фабрика, что напротив Черноголовского пруда, знаменита своими световыми стеклянными куполами.
Московский областной театр драмы и комедии, расположенный в Ногинске, также можео назвать местной достопримечательностью. Его знают многие жители Подмосковья. Он открылся как синематограф «Колизей» в 1914 году. При рабочих клубах Глуховской и Истомкинской мануфактур существовали драматические кружки. Любительские постановки выносились на суд зрителей в «Колизее». В этих спектаклях нередко принимали участие такие известные артисты московских сцен, как Книппер-Чехова, Качалов, Тарханов, Москвин.
Также широко известны красивейшая школа России - №10, 1908 года постройки и двуклассное училище при Богородско-Глуховской мануфактуре Арсения Морозова.
Фото - Школа №10
Здание школы №2 имени Короленко - объект культурного наследия регионального значения. Бывшая женская гимназия, построенная в 1908 году в стиле модерн по проекту архитектора Александра Кузнецова — основателя отечественной школы промышленной архитектуры. В Богородске им построены не только здание женской гимназии, но и Новоткацкая фабрика.
На стадионе "Знамя" в Глухово расположен старейший велотрек в России. Там же в 1909 году из числа рабочих текстильных фабрик была образована одна из первых футбольных команд в России.
Памятный знак воинам 209-го пехотного Богородского полка, павшим в боях Первой мировой войны установлен в центре Ногинска. Легендарный полк сформировали в 1913 году. С ним связана история подвига русских солдат при Осовце и создание иконописного образа явления Богородицы "Августовская победа".
Фото - Вокзал
Улицы Богородска хранят память о многих знаменитостях. Здесь останавливались А. В. Суворов, А. С. Пушкин, в городском училище преподавал известный философ Н. Ф. Фёдоров.
В советское время город прославился тем, что в нем был установлен первый в мире памятник В. И. Ленину, созданный декоратором Глуховской мануфактуры Федором Кузнецовым.

**Comment by OlgaGost** [comment]
https://disk.yandex.ru/d/J6SrXdk41-qGEQ

-

**Comment by TorinAsakura** [comment]
@OlgaGost 3 фотографии для целой страницы? Я говорил о дюжине или хотя бы половины от неё, но никак не 3

**Comment by TorinAsakura** [comment]
@OlgaGost сделать мета-описание карточке SEO блока

**Comment by TorinAsakura** [comment]
@OlgaGost https://bogorodsky.online/o-bogorodskom-okruge/istoriya/
