### ISSUE TITLE
Храмы

### ISSUE THREAD

**Issue by OlgaGost** [torin-asakura/bogorodsky#16]
https://disk.yandex.ru/d/BikyIt_jztV2LQ

**Comment by OlgaGost** [comment]
https://disk.yandex.ru/d/BikyIt_jztV2LQ

**Comment by TorinAsakura** [comment]
@OlgaGost сделать мета-описание карточке SEO блока

**Comment by TorinAsakura** [comment]
@OlgaGost https://bogorodsky.online/o-bogorodskom-okruge/hramy-bogorodskogo-okruga/
